# This rule is not used by the project cinder-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to cinder.openstack.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cinder-operator
    app.kubernetes.io/managed-by: kustomize
  name: cinderscheduler-viewer-role
rules:
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cinder.openstack.org
  resources:
  - cinderschedulers/status
  verbs:
  - get
