# To be able to use this sample it is necessary to:
# - Have a 3PAR backend with iSCSI support
# - Have the 3PAR credentials in cinder-volume-3par-secrets.yaml
# - Having iscsid and multpathd running on the host (automatically done by this sample)
# - Build a cinder-volume container with the 3parclient cinder driver dependency, make it available in a registry accessible by OpenShift, and set its location in this file's containerImage
#
# There is a sample Dockerfile in the parent directory showing how the cinder-volume container in this containerImage was created.
# The correct way to configure and run the daemons is using `MachineConfig` as shown in `iscsid.yaml` and `multipathd.yaml`, like this sample does.
#
# ATTENTION: After applying this OpenShift nodes will reboot, because of the `MachineConfig` changes and will take a while to recover.

apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  cinder:
    template:
      cinderVolumes:
        hpe3par-iscsi:
          networkAttachments:
          - storage
          # This image exists and was built using the Dockerfile available in the grandparent directory
          containerImage: quay.io/geguileo/podified-antelope-openstack-cinder-volume-3par:current-podified
          customServiceConfigSecrets:
            - cinder-volume-3par-secrets
          customServiceConfig: |
            [hpe3par]
            volume_backend_name=hpe3par
            volume_driver = cinder.volume.drivers.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
            hpe3par_debug=False
            hpe3par_iscsi_chap_enabled=false
            hpe3par_snapshot_retention=48
            hpe3par_snapshot_expiration=72
